# Generated by Django 5.1.1 on 2024-10-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_webtoons"),
    ]

    operations = [
        migrations.AddField(
            model_name="webtoons",
            name="brief_description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="webtoons",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
