# Generated by Django 5.1.1 on 2024-10-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_webtoons_brief_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webtoons",
            name="creator",
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="webtoons",
            name="genre",
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="webtoons",
            name="title",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
