# Generated by Django 5.1.1 on 2024-10-12 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_webtoons_creator_alter_webtoons_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webtoons",
            name="thumbnile",
            field=models.ImageField(upload_to="thumbline/"),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=50)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "webtoon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="api.webtoons",
                    ),
                ),
            ],
        ),
    ]
