# Generated by Django 5.1.1 on 2024-10-12 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_webtoons_thumbnile_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="author",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="created_at",
        ),
    ]
